### ISSUE TITLE
add_linP_params module in notebooks

### ISSUE THREAD

**Issue by armengau** [igmhub/cup1d#27]
The module cup1d.planck.add_linP_params is not in this public version,
- it is asked in notebooks planck/plot[test]_planck_linP.ipynb, but not needed
- it is obviously needed for planck/add_linP_chains.ipynb

**Comment by andreufont** [comment]
Could you check out the new branch `fix_add_linP`? I forgot to update that module, since we only used it in old notebooks.
https://github.com/igmhub/cup1d/tree/fix_add_linP

I checked that I was able to call that function, but not in the context of the notebooks (I don't have the original Planck chains anymore...)

**Comment by andreufont** [comment]
I also updated the notebook `add_linP_params`, let me know if you can run it successfully and I will merge that branch and close the issue.

**Comment by armengau** [comment]
Yes, I checked the notebook `add_linP_chains` works now.

**Comment by andreufont** [comment]
solved in PR #28
