### ISSUE TITLE
Unclear instructions

### ISSUE THREAD

**Issue by p-slash** [igmhub/cup1d#63]
tutorial notebooks seem to be deleted from the repo. I cannot figure out what is the actual pipeline script and how to run it. sam_sim.py is broken since SamplerPipeline has moved to another module. When I fixed that, I get the error `ModuleNotFoundError: No module named 'GPy'`. If Gpy is required please add it to the requirements for the installation.
Help appreciated. Thanks.

**Comment by jchavesmontero** [comment]
As you can see in the lace readme, if you want to use the GP emulators, you need to do

pip install -e .[gpy]

Since this is not mentioned in the cup1d instructions directly (sorry about that), I will update the cup1d readme so it does not happen to people not familiar with lace. The motivation for not installing gpy by default is incompatibilities with old clusters.

**Comment by jchavesmontero** [comment]
The notebook is here https://github.com/igmhub/cup1d/blob/main/notebooks/tutorials/sample_sim.ipynb, sorry, it got deleted when moving the data

**Comment by jchavesmontero** [comment]
I have just fixed the issue you mentioned with SamplerPipeline, sam_sim.py should work for you now.
